---
- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: admin_user_name
      prompt: domain admin (enter if skipped)
    - name: admin_password
      prompt: domain admin password (enter if skipped)
  vars:
    input: &input
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
  vars_files:
    - globals.yml
  tasks:
  - name: Get Ontapi version
   na_ontap_gather_facts:
      state: info
      <<: *input
      https: true
      ontapi: 32
      validate_certs: false
  - import_role:
      name: na_ontap_cluster_config
    vars:
      <<: *input
  - import_role:
      name: na_ontap_vserver_create
    vars:
      <<: *input
    when: vservers != None