---
- hosts: localhost
  name: Setup SVM
  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: "{{ state }}"
      name: "{{ vserver }}"
      root_volume: "{{ vserver}}_root"
      root_volume_aggregate: "{{ aggr }}"
      root_volume_security_style: unix
      <<: *login
  - name: Create interface
    na_ontap_interface:
      state: "{{ state }}"
      interface_name: "{{ vserver }}_mgmt_data_1"
      home_port: e0b
      home_node: Q100BTCS001-01
      role: data
      protocols: nfs
      admin_status: up
      failover_policy: local-only
      firewall_policy: mgmt
      is_auto_revert: true
      address: "{{ address }}"
      netmask: 255.255.255.0
      vserver: "{{ vserver }}"
      <<: *login
  - name: change nfs status
    na_ontap_nfs:
      state: "{{ state }}"
      service_state: started
      vserver: "{{ vserver }}"
      nfsv3: enabled
      nfsv4: enabled
      nfsv41: disabled
      tcp: enabled
      udp: enabled
      vstorage_state: disabled
      <<: *login
  - name: Setup default rules
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: default
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: none
      super_user_security: none
      <<: *login
  - name: Create User Role
    na_ontap_user_role:
      state: "{{ state }}"
      name: "Netapp-Harvest-Role"
      command_directory_name: "{{ item.directory }}"
      access_level: "{{ item.access_level }}"
      vserver: Q100BTCS001
      <<: *login
    with_items:
      - { directory: version, access_level: readonly}
      - { directory: "cluster identity show", access_level: readonly}
      - { directory: "cluster show", access_level: readonly}
      - { directory: "system node show", access_level: readonly}
      - { directory: "network interface show", access_level: readonly}
      - { directory: "qos workload show", access_level: readonly}
      - { directory: statistics, access_level: readonly}
      - { directory: "lun show", access_level: readonly}
